{% set name = "dmgbuild" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dba01d29f10c6804f2d72301600ddd03724daa41cd21a95409c44a3e199b19aa

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - dmgbuild = dmgbuild.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - importlib_resources >=5.9
    - ds_store >=1.1.0
    - mac_alias >=2.0.1
    - __osx

test:
  imports:
    - dmgbuild
  requires:
    - pip
    - pytest
    - pytest-cov
    - tox
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - tox -e py

about:
  home: https://github.com/dmgbuild/dmgbuild
  doc_url: https://dmgbuild.readthedocs.io/en/latest/
  summary: macOS command line utility to build disk images
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotduarte
