schema_version: 1

context:
  name: dmgbuild
  version: "1.6.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 72ce448feec6aa24dba5e777c44a0397b7ae1b4d86fb4dd537e44cf1653c03ec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dmgbuild = dmgbuild.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - importlib_resources >=5.9
    - ds_store >=1.1.0
    - mac_alias >=2.0.1
    - __osx

tests:
  - python:
      imports:
        - dmgbuild
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - pip
        - pytest
        - pytest-cov
        - tox
        - python ${{ python_min }}.*
    script:
      - tox -e py

about:
  summary: macOS command line utility to build disk images
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/dmgbuild/dmgbuild
  documentation: https://dmgbuild.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - marcelotduarte
